name: Build binaries

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux-build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
        platform:
          - name: linux
            os: ubuntu-20.04
          - name: windows
            os: ubuntu-20.04

    steps:
      - name: Setup ubuntu container
        run: |
          apt update
          apt install -yqq build-essential make software-properties-common
          add-apt-repository -y ppa:git-core/ppa
          apt update && apt install -yqq git zip unzip zlib1g-dev zlib1g yasm

      - name: Check out code
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.ref }}

      - name: Set up go
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
          cache: true
          cache-dependency-path: go.sum

      - name: Cache ffmpeg
        id: cache-ffmpeg
        uses: actions/cache@v3
        with:
          path: /home/runner/compiled
          key: ${{ runner.os }}-${{ matrix.platform.name }}-${{ matrix.arch }}-ffmpeg-${{ hashFiles('**/install_ffmpeg.sh') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform.name }}-${{ matrix.arch }}-ffmpeg-

      - name: Set build environment
        run: |
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "GOOS=${{ matrix.platform.name }}" >> $GITHUB_ENV
          echo "GO_BUILD_DIR=lp-builds/" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/github/home/compiled/lib/pkgconfig" >> $GITHUB_ENV

      - name: Set GPU build environment
        if: matrix.hardware.type == 'gpu'
        run: |
          echo "CPATH=/usr/local/cuda_${{ matrix.arch }}/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=/usr/local/cuda_${{ matrix.arch }}/lib64" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L/usr/local/cuda_${{ matrix.arch }}/lib64" >> $GITHUB_ENV
          echo "RELEASE_TAG=gpu" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          apt update \
            && apt install -yqq software-properties-common curl apt-transport-https lsb-release \
            && curl -fsSl https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
            && add-apt-repository "deb https://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-12 main" \
            && apt update \
            && apt -yqq install \
              clang-12 clang-tools-12 lld-12 build-essential pkg-config autoconf git python \
              gcc-multilib gcc-mingw-w64 libgcc-9-dev-arm64-cross mingw-w64-tools gcc-mingw-w64-x86-64

          update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 30 \
            && update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 30 \
            && update-alternatives --install /usr/bin/ld ld /usr/bin/lld-12 30

      - name: Install go modules
        if: steps.go.outputs.cache-hit != 'true'
        run: go mod download

      - name: Install ffmpeg
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: ./install_ffmpeg.sh

      - name: Build binaries
        run: |
          git config --global --add safe.directory '*'
          ./ci_env.sh make

      - name: Upload build
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
          GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}
          DISCORD_URL: ${{ secrets.DISCORD_URL }}
        run: ./upload_build.sh

      - name: Upload artifacts for cutting release
        uses: actions/upload-artifact@master
        with:
          name: release-artifacts
          path: releases/
