name: Create release on github

on:
  workflow_run:
    workflows:
      - Build binaries
    types:
      - "completed"

jobs:
  release:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download artifacts from build stage
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          name: release-artifacts
          path: releases/
      - name: Get short hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Create and Push Tag
        run: |
          TAG_NAME=${{ github.event.workflow_run.head_branch }}.${{ steps.vars.outputs.sha_short }}
          git tag $TAG_NAME
          git push origin $TAG_NAME
      - name: Release to github
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}.${{ steps.vars.outputs.sha_short }}
          files: |
            releases/*
